<?php
/**
 * inc/bail_habitation_annexes.php — Annexes FIGÉES du bail habitation nu (loi 89-462) :
 *   1) Décret n° 87-713 du 26 août 1987 — liste des charges récupérables
 *   2) Décret n° 87-712 du 26 août 1987 — liste des réparations locatives
 *   3) Notice légale d'information (droits et obligations des parties)
 *
 * Texte statique verbatim (identique pour toute location) → aucun champ à remplir.
 * bail_habitation_build_pdf() l'ajoute automatiquement après le corps.
 */
declare(strict_types=1);

if (!function_exists('bail_habitation_annexes_html')) {
    function bail_habitation_annexes_html(): string
    {
        $h  = '<div class="annexe">';

        // ── 1) DÉCRET 87-713 — CHARGES RÉCUPÉRABLES ──
        $h .= '<h2>Décret n° 87-713 du 26 août 1987 fixant la liste des charges récupérables</h2>';
        $h .= '<p><b>Article 1.</b> La liste des charges récupérables prévue à l\'article 18 de la loi du 23 décembre 1986 susvisée figure en annexe au présent décret.</p>';
        $h .= '<p><b>Article 2.</b> Pour l\'application du présent décret : a) Il n\'y a pas lieu de distinguer entre les services assurés par le bailleur en régie et ceux assurés dans le cadre d\'un contrat d\'entreprise. Le coût des services en régie inclut les dépenses de personnel d\'encadrement technique chargé du contrôle direct du gardien, du concierge ou de l\'employé d\'immeuble, exigibles à concurrence de 10 % de leur montant. b) Les dépenses de personnel récupérables correspondent à la rémunération et aux charges sociales et fiscales. c) Le gardien ou concierge assurant l\'entretien des parties communes et l\'élimination des rejets : dépenses exigibles à concurrence de 75 % ; une seule des deux tâches : 40 %. d) L\'employé d\'immeuble : dépenses exigibles en totalité. Ne sont pas retenus : salaire en nature, intéressement et participation, indemnités de départ à la retraite, indemnités de licenciement, cotisation mutuelle prise en charge par l\'employeur, participation au comité d\'entreprise, participation à l\'effort de construction, cotisation à la médecine du travail. e) Le remplacement d\'éléments d\'équipement n\'est assimilable aux menues réparations que si son coût est au plus égal au coût de celles-ci.</p>';
        $h .= '<p><b>Article 3.</b> Les dépenses afférentes à l\'entretien courant et aux menues réparations d\'installations individuelles (III de l\'annexe) sont récupérables lorsqu\'elles sont effectuées par le bailleur au lieu et place du locataire.</p>';
        $h .= '<p class="clabel">Annexe : Liste des charges récupérables</p>';
        $h .= '<p><b>I. Ascenseurs et monte-charge.</b> 1. Électricité. 2. Exploitation, entretien courant, menues réparations : visite périodique, nettoyage et graissage des organes mécaniques ; examen semestriel des câbles et vérification annuelle des parachutes ; nettoyage annuel de la cuvette, du dessus de la cabine et de la machinerie ; dépannage sans réparation ni fourniture de pièces ; tenue du dossier d\'entretien. Fournitures (produits, petit matériel, lampes de cabine). Menues réparations de la cabine, des paliers, des balais du moteur et fusibles.</p>';
        $h .= '<p><b>II. Eau froide, eau chaude et chauffage collectif des locaux privatifs et des parties communes.</b> Dépenses relatives à l\'eau (froide/chaude, entretien courant, espaces extérieurs, taxes et redevances y compris assainissement), aux produits de traitement de l\'eau, à l\'électricité, au combustible ou à la fourniture d\'énergie. Exploitation et entretien courant (nettoyage des brûleurs, graissage des pompes, réglage des appareils de régulation, ramonage, conduite de chauffage, relevé des compteurs, entretien de l\'adoucisseur, contrôles fluide frigorigène des PAC, nettoyage des capteurs solaires…). Menues réparations dans les parties communes (fuites, joints, presse-étoupes, recharge fluide frigorigène).</p>';
        $h .= '<p><b>III. Installations individuelles.</b> Chauffage, production d\'eau chaude, distribution d\'eau dans les parties privatives : combustible commun ; exploitation et entretien courant (réglage ECS, vérification des appareils de commande et sécurité, dépannage, contrôle des chauffe-eau électriques, réglage des thermostats, contrôle des groupes de sécurité…) ; menues réparations (remplacement de bilames, pistons, membranes, boîtes à eau, allumage piézo-électrique, clapets et joints des appareils à gaz ; rinçage des corps de chauffe ; remplacement des joints, clapets et presse-étoupes des robinets ; remplacement des joints et flotteurs des chasses d\'eau).</p>';
        $h .= '<p><b>IV. Parties communes intérieures.</b> Électricité ; fournitures consommables (produits d\'entretien, balais, sel…) ; entretien de la minuterie, pose/entretien des tapis ; menues réparations des appareils d\'entretien (aspirateur) ; entretien de propreté (frais de personnel).</p>';
        $h .= '<p><b>V. Espaces extérieurs.</b> Électricité, essence et huile, fournitures consommables (ampoules, engrais, produits phytosanitaires, graines et plants de remplacement) ; exploitation et entretien courant (coupe, désherbage, ratissage, nettoyage, arrosage des allées, espaces verts, aires de jeux, bassins et canalisations ; entretien du matériel horticole ; remplacement du sable des bacs) ; peinture et menues réparations des bancs, équipements de jeux et grillages.</p>';
        $h .= '<p><b>VI. Hygiène.</b> Fournitures consommables (sacs d\'élimination des rejets, produits de désinsectisation/désinfection) ; entretien et vidange des fosses d\'aisances, entretien des appareils de conditionnement des ordures ; élimination des rejets (frais de personnel).</p>';
        $h .= '<p><b>VII. Équipements divers du bâtiment.</b> Énergie de la ventilation mécanique ; ramonage des conduits de ventilation, entretien de la VMC, des dispositifs d\'ouverture automatique/codée et des interphones ; abonnement des postes de téléphone à la disposition des locataires.</p>';
        $h .= '<p><b>VIII. Impositions et redevances.</b> Droit de bail ; taxe ou redevance d\'enlèvement des ordures ménagères ; taxe de balayage.</p>';

        // ── 2) DÉCRET 87-712 — RÉPARATIONS LOCATIVES ──
        $h .= '<h2>Décret n° 87-712 du 26 août 1987 fixant la liste des réparations locatives</h2>';
        $h .= '<p><b>Article 1.</b> Sont des réparations locatives les travaux d\'entretien courant et de menues réparations, y compris les remplacements d\'éléments assimilables, consécutifs à l\'usage normal des locaux et équipements à usage privatif, notamment ceux énumérés en annexe.</p>';
        $h .= '<p class="clabel">Annexe : Liste des réparations ayant le caractère de réparations locatives</p>';
        $h .= '<p><b>I. Parties extérieures à usage exclusif.</b> a) Jardins privatifs : entretien courant (allées, pelouses, massifs, bassins et piscines), taille, élagage, échenillage ; remplacement des arbustes ; réparation et remplacement des installations mobiles d\'arrosage. b) Auvents, terrasses, marquises : enlèvement de la mousse et végétaux. c) Descentes d\'eaux pluviales, chéneaux et gouttières : dégorgement des conduits.</p>';
        $h .= '<p><b>II. Ouvertures intérieures et extérieures.</b> a) Portes et fenêtres : graissage des gonds, paumelles et charnières ; menues réparations des boutons, poignées, gonds, crémones, espagnolettes ; remplacement de boulons, clavettes et targettes. b) Vitrages : réfection des mastics, remplacement des vitres détériorées. c) Stores et jalousies : graissage, remplacement de cordes, poulies ou lames. d) Serrures et verrous : graissage, remplacement de petites pièces et des clés. e) Grilles : nettoyage, graissage, remplacement de petites pièces.</p>';
        $h .= '<p><b>III. Parties intérieures.</b> a) Plafonds, murs, cloisons : maintien en état de propreté ; menus raccords de peintures et tapisseries ; remplacement de quelques éléments de revêtement (faïence, mosaïque, matière plastique) ; rebouchage des trous. b) Parquets, moquettes et revêtements de sol : encaustiquage, entretien de la vitrification ; remplacement de quelques lames, pose de raccords. c) Placards et menuiseries : remplacement des tablettes et tasseaux, réparation des dispositifs de fermeture, fixation de raccords.</p>';
        $h .= '<p><b>IV. Plomberie.</b> a) Canalisations d\'eau : dégorgement, remplacement de joints et colliers. b) Canalisations de gaz : entretien des robinets, siphons et ouvertures d\'aération, remplacement des tuyaux souples. c) Fosses septiques, puisards : vidange. d) Chauffage, ECS et robinetterie : remplacement des bilames, pistons, membranes, clapets et joints des appareils à gaz ; rinçage des corps de chauffe ; remplacement des joints et presse-étoupes des robinets et chasses d\'eau. e) Éviers et appareils sanitaires : nettoyage du calcaire, remplacement des flexibles de douche.</p>';
        $h .= '<p><b>V. Électricité.</b> Remplacement des interrupteurs, prises, coupe-circuits, fusibles, ampoules et tubes ; réparation ou remplacement des baguettes ou gaines de protection.</p>';
        $h .= '<p><b>VI. Autres équipements mentionnés au contrat.</b> Entretien courant et menues réparations des appareils (réfrigérateurs, lave-linge, lave-vaisselle, sèche-linge, hottes, adoucisseurs, capteurs solaires, PAC, climatiseurs, antennes individuelles, meubles scellés, cheminées, glaces et miroirs) ; menues réparations liées à la dépose des bourrelets ; graissage et remplacement des joints des vidoirs ; ramonage des conduits d\'évacuation des fumées, gaz et ventilation.</p>';

        // ── 3) NOTICE LÉGALE D'INFORMATION (synthèse fidèle) ──
        $h .= '<h2>Notice légale d\'information</h2>';
        $h .= '<p class="sub2">Rappel des principaux droits et obligations des parties (loi n° 89-462 du 6 juillet 1989) et des voies de conciliation et de recours. Certaines règles connaissent des aménagements pour les locations meublées ou les colocations.</p>';

        $h .= '<p class="clabel">1. Établissement du bail</p>';
        $h .= '<p><b>1.1. Forme et contenu.</b> Le contrat est établi par écrit et respecte un bail type défini par décret. Il comporte l\'identité des parties, la description du logement, sa surface habitable et les conditions financières. En cas d\'inexactitude supérieure à 5 % de la surface habitable d\'une location nue, le locataire peut demander une diminution de loyer proportionnelle. Certaines clauses sont réputées non écrites (prélèvement automatique imposé, pénalités de retard, interdiction d\'héberger, frais de quittance…). Le bailleur remet un dossier de diagnostic technique incluant le DPE (art. 3-3).</p>';
        $h .= '<p><b>1.2. Durée.</b> Location nue : 3 ans minimum lorsque le bailleur est une personne physique ou une SCI familiale, 6 ans lorsqu\'il est une personne morale ; reconduction ou renouvellement à défaut de congé. La durée peut être réduite (au minimum 1 an) si le bailleur personne physique prévoit de reprendre le logement pour raison familiale ou professionnelle, mentionnée au bail. Location meublée : 1 an (9 mois non reconductibles pour un étudiant).</p>';
        $h .= '<p><b>1.3. Conditions financières.</b> Le loyer initial est fixé librement, sauf logements classés F ou G (aucune augmentation à la relocation) et zones tendues (encadrement : évolution plafonnée à la relocation, et le cas échéant loyer de référence majoré + complément de loyer justifié). Révision annuelle possible si une clause le prévoit, dans la limite de l\'IRL (impossible pour les passoires F/G). Ajustement au renouvellement seulement si le loyer est manifestement sous-évalué (hors F/G), selon la procédure et l\'étalement prévus par la loi. Charges récupérables (art. 23) par provisions avec régularisation annuelle, ou au forfait pour meublé/colocation. Contribution au partage des économies de charges (art. 23-1) possible après travaux d\'économie d\'énergie. Modalités de paiement : quittance gratuite sur demande, sans frais.</p>';
        $h .= '<p><b>1.4. Garanties.</b> Dépôt de garantie : ≤ 1 mois de loyer hors charges (location nue), ≤ 2 mois (meublé), non révisable. Garantie autonome possible en lieu et place. Cautionnement : acte écrit signé par la caution comportant les mentions obligatoires ; le bailleur ne peut cumuler caution et assurance des risques locatifs (sauf étudiant/apprenti).</p>';
        $h .= '<p><b>1.5. État des lieux (art. 3-2).</b> Établi contradictoirement à l\'entrée et à la sortie ; à défaut d\'état des lieux d\'entrée, le logement est présumé délivré en bon état. Le locataire peut demander à le compléter dans les dix jours (ou durant le premier mois de chauffe pour le chauffage). En cas de désaccord, recours à un commissaire de justice, frais partagés par moitié.</p>';

        $h .= '<p class="clabel">2. Droits et obligations des parties</p>';
        $h .= '<p><b>2.1. Le BAILLEUR</b> (art. 6) doit délivrer un logement décent et en bon état, respectant les critères de performance énergétique minimale (calendrier F/E/D), l\'entretenir et y faire les réparations autres que locatives, assurer une jouissance paisible, ne pas s\'opposer aux simples aménagements, et transmettre les informations de consommation (chaleur, froid, eau chaude) et de qualité de l\'eau.</p>';
        $h .= '<p><b>2.2. Le LOCATAIRE</b> (art. 7) doit payer le loyer et les charges aux dates convenues, user paisiblement du logement conformément à sa destination et au règlement de copropriété, ne pas sous-louer sans accord écrit, ne pas réaliser de travaux de transformation sans accord, prendre en charge l\'entretien courant et les réparations locatives, répondre des dégradations, et s\'assurer contre les risques locatifs (justification annuelle).</p>';
        $h .= '<p><b>2.3. Lutte contre les nuisibles.</b> Le bailleur délivre un logement exempt d\'infestation et le maintient décent ; le locataire suit les recommandations (stop-punaises.gouv.fr), informe le bailleur et permet l\'accès pour les traitements.</p>';

        $h .= '<p class="clabel">3. Fin de contrat et sortie du logement</p>';
        $h .= '<p><b>3.1. Congés (art. 15 et 25-8).</b> Le locataire peut donner congé à tout moment (préavis 3 mois en nu, réduit à 1 mois en zone tendue ou motifs prévus ; 1 mois en meublé) par LRAR, acte de commissaire de justice ou remise en main propre. Le bailleur ne peut donner congé qu\'à l\'échéance et pour reprise, vente ou motif légitime et sérieux (préavis 6 mois en nu, 3 mois en meublé, avec les notices et mentions obligatoires). Le congé frauduleux est sanctionné (amende jusqu\'à 6 000 € / 30 000 € pour une personne morale).</p>';
        $h .= '<p><b>3.2. Sortie.</b> État des lieux de sortie ; restitution du dépôt de garantie dans un délai maximal de 2 mois (1 mois si l\'état des lieux de sortie est conforme), justifiée par des documents ; majoration de 10 % du loyer mensuel par mois de retard commencé.</p>';

        $h .= '<p class="clabel">4. Départ du conjoint victime de violences (art. 8-2)</p>';
        $h .= '<p>Le conjoint, partenaire de PACS ou concubin notoire quittant le logement en raison de violences peut, sur justification (ordonnance de protection ou condamnation de moins de six mois), mettre fin à sa solidarité et à celle de sa caution le lendemain de la première présentation du courrier au bailleur.</p>';

        $h .= '<p class="clabel">5. Règlement des litiges locatifs</p>';
        $h .= '<p>Prescription de principe : 3 ans (1 an pour l\'action en révision de loyer). Règlement amiable conseillé, puis <b>commission départementale de conciliation</b> (gratuite ; saisine préalable obligatoire pour certains litiges d\'encadrement/renouvellement de loyer). À défaut, saisine du tribunal judiciaire du lieu du logement. Résiliation par mise en œuvre de la clause résolutoire (commandement de payer, délai de 2 mois ; 1 mois pour défaut d\'assurance) ou résiliation judiciaire ; assignation par commissaire de justice, notification au préfet et diagnostic social et financier ; le juge peut accorder des délais de paiement (jusqu\'à 3 ans) ou ordonner l\'expulsion.</p>';
        $h .= '<p>Prévention des expulsions : fonds de solidarité pour le logement (FSL), commission de surendettement, CCAPEX. Recherche d\'un logement adapté et DALO. <b>Procédure d\'expulsion</b> : uniquement sur décision de justice (l\'expulsion par le bailleur lui-même est passible de 3 ans de prison et 30 000 € d\'amende) ; commandement de quitter les lieux, délai de 2 mois, concours de la force publique. <b>Trêve hivernale</b> du 1<sup>er</sup> novembre au 31 mars.</p>';

        $h .= '<p class="clabel">6. Contacts utiles</p>';
        $h .= '<p>ADIL (agences départementales d\'information sur le logement, www.anil.org) ; organismes payeurs des aides (CAF, MSA) ; associations représentatives des bailleurs (UNPI, FEI, UDLI) et des locataires (CNL, CGL, CSF, CLCV, AFOC) ; maisons de justice et du droit ; service-public.fr ; Allo Service Public 3939 ; DossierFacile (dossierfacile.fr).</p>';

        $h .= '</div>';
        return $h;
    }
}
