<?php
/**
 * inc/bail_habitation_annexes.php — Annexes VERBATIM du bail habitation nu (loi 89-462) :
 *   1) Décret n° 87-713 du 26 août 1987 — liste des charges récupérables
 *   2) Décret n° 87-712 du 26 août 1987 — liste des réparations locatives
 *   3) Notice légale d'information (droits et obligations des parties)
 *
 * Texte statique intégral (identique pour toute location) → aucun champ à remplir.
 * bail_habitation_build_pdf() l'ajoute automatiquement après le corps.
 */
declare(strict_types=1);

if (!function_exists('bail_habitation_annexes_html')) {
    function bail_habitation_annexes_html(): string
    {
        $h = '<div class="annexe">';

        /* ═══════════════ 1) DÉCRET 87-713 — CHARGES RÉCUPÉRABLES ═══════════════ */
        $h .= '<h2>Décret n° 87-713 du 26 août 1987 fixant la liste des charges récupérables</h2>';
        $h .= '<p><b>Article 1.</b> La liste des charges récupérables prévue à l\'article 18 de la loi du 23 décembre 1986 susvisée figure en annexe au présent décret.</p>';
        $h .= '<p><b>Article 2.</b> Pour l\'application du présent décret :</p>';
        $h .= '<p>a) Il n\'y a pas lieu de distinguer entre les services assurés par le bailleur en régie et les services assurés dans le cadre d\'un contrat d\'entreprise. Le coût des services assurés en régie inclut les dépenses de personnel d\'encadrement technique chargé du contrôle direct du gardien, du concierge ou de l\'employé d\'immeuble ; ces dépenses d\'encadrement sont exigibles au titre des charges récupérables à concurrence de 10 % de leur montant. Lorsqu\'il existe un contrat d\'entreprise, le bailleur doit s\'assurer que ce contrat distingue les dépenses récupérables et les autres dépenses ;</p>';
        $h .= '<p>b) Les dépenses de personnel récupérables correspondent à la rémunération et aux charges sociales et fiscales ;</p>';
        $h .= '<p>c) Lorsque le gardien ou le concierge d\'un immeuble ou d\'un groupe d\'immeubles assure, conformément à son contrat de travail, l\'entretien des parties communes et l\'élimination des rejets, les dépenses correspondant à sa rémunération et aux charges sociales et fiscales y afférentes sont exigibles au titre des charges récupérables à concurrence de 75 % de leur montant, y compris lorsqu\'un tiers intervient pendant les repos hebdomadaires et les congés prévus dans les clauses de son contrat de travail, ainsi qu\'en cas de force majeure, d\'arrêt de travail ou en raison de l\'impossibilité matérielle ou physique temporaire pour le gardien ou le concierge d\'effectuer seul les deux tâches. Ces dépenses ne sont exigibles qu\'à concurrence de 40 % de leur montant lorsque le gardien ou le concierge n\'assure, conformément à son contrat de travail, que l\'une ou l\'autre des deux tâches. Un couple de gardiens ou de concierges qui assure, dans le cadre d\'un contrat de travail commun, l\'entretien des parties communes et l\'élimination des rejets est assimilé à un personnel unique pour l\'application du présent article. Les éléments suivants ne sont pas retenus : le salaire en nature ; l\'intéressement et la participation aux bénéfices de l\'entreprise ; les indemnités et primes de départ à la retraite ; les indemnités de licenciement ; la cotisation à une mutuelle prise en charge par l\'employeur ou par le comité d\'entreprise ; la participation de l\'employeur au comité d\'entreprise ; la participation de l\'employeur à l\'effort de construction ; la cotisation à la médecine du travail ;</p>';
        $h .= '<p>d) Lorsqu\'un employé d\'immeuble assure, conformément à son contrat de travail, l\'entretien des parties communes ou l\'élimination des rejets, les dépenses correspondant à sa rémunération et aux charges sociales et fiscales y afférentes sont exigibles, en totalité, au titre des charges récupérables. Les mêmes éléments qu\'au c) ne sont pas retenus ;</p>';
        $h .= '<p>e) Le remplacement d\'éléments d\'équipement n\'est considéré comme assimilable aux menues réparations que si son coût est au plus égal au coût de celles-ci.</p>';
        $h .= '<p><b>Article 3.</b> Pour l\'application du présent décret, les dépenses afférentes à l\'entretien courant et aux menues réparations d\'installations individuelles, qui figurent au III du tableau annexé, sont récupérables lorsqu\'elles sont effectuées par le bailleur au lieu et place du locataire.</p>';
        $h .= '<p><b>Article 3 bis.</b> Le présent décret est applicable en Polynésie française pour la mise en œuvre des dispositions de l\'article 23 de la loi n° 89-462 du 6 juillet 1989.</p>';
        $h .= '<p><b>Article 4.</b> Le ministre d\'État, ministre de l\'économie, des finances et de la privatisation, le garde des sceaux, ministre de la justice, et le ministre de l\'équipement, du logement, de l\'aménagement du territoire et des transports sont chargés, chacun en ce qui le concerne, de l\'exécution du présent décret, qui sera publié au Journal officiel de la République française.</p>';
        $h .= '<p class="clabel">Annexe : Liste des charges récupérables</p>';
        $h .= '<p><b>I. — Ascenseurs et monte-charge.</b> 1. Dépenses d\'électricité. 2. Dépenses d\'exploitation, d\'entretien courant, de menues réparations : a) Exploitation : visite périodique, nettoyage et graissage des organes mécaniques ; examen semestriel des câbles et vérification annuelle des parachutes ; nettoyage annuel de la cuvette, du dessus de la cabine et de la machinerie ; dépannage ne nécessitant pas de réparations ou fournitures de pièces ; tenue d\'un dossier par l\'entreprise d\'entretien mentionnant les visites techniques, incidents et faits importants touchant l\'appareil. b) Fournitures relatives à des produits ou à du petit matériel d\'entretien (chiffons, graisses et huiles nécessaires) et aux lampes d\'éclairage de la cabine. c) Menues réparations : de la cabine (boutons d\'envoi, paumelles de portes, contacts de portes, ferme-portes automatiques, coulisseaux de cabine, dispositif de sécurité de seuil et cellule photo-électrique) ; des paliers (ferme-portes mécaniques, électriques ou pneumatiques, serrures électromécaniques, contacts de porte et boutons d\'appel) ; des balais du moteur et fusibles.</p>';
        $h .= '<p><b>II. — Eau froide, eau chaude et chauffage collectif des locaux privatifs et des parties communes.</b> 1. Dépenses relatives à l\'eau froide et chaude des locataires ou occupants ; à l\'eau nécessaire à l\'entretien courant des parties communes (y compris la station d\'épuration) et des espaces extérieurs (ensemble des taxes et redevances, y compris la redevance d\'assainissement) ; aux produits nécessaires à l\'exploitation, à l\'entretien et au traitement de l\'eau ; à l\'électricité ; au combustible ou à la fourniture d\'énergie, quelle que soit sa nature. 2. Dépenses d\'exploitation, d\'entretien courant et de menues réparations : a) Exploitation et entretien courant : nettoyage des gicleurs, électrodes, filtres et clapets des brûleurs ; entretien et graissage des pompes de relais, jauges, contrôleurs de niveau, groupes moto-pompes et pompes de puisards ; graissage des vannes et robinets et réfection des presse-étoupes ; remplacement des ampoules des voyants lumineux et de chaufferie ; entretien et réglage des appareils de régulation automatique ; vérification et entretien des régulateurs de tirage ; réglage des vannes, robinets et tés (hors équilibrage) ; purge des points de chauffage ; frais de contrôles de combustion ; entretien des épurateurs de fumée ; opérations de mise en repos de fin de saison, rinçage des corps de chauffe et tuyauteries, nettoyage des chaufferies, puisards et siphons, ramonage des chaudières, carneaux et cheminées ; conduite de chauffage ; frais de location, d\'entretien et de relevé des compteurs généraux et individuels ; entretien de l\'adoucisseur, du détartreur, du surpresseur et du détendeur ; contrôles périodiques anti-fuites de fluide frigorigène et entretien des pompes à chaleur ; nettoyage et graissage des organes des capteurs solaires. b) Menues réparations dans les parties communes ou sur des éléments d\'usage commun : réparation de fuites sur raccords et joints ; remplacement des joints, clapets et presse-étoupes ; rodage des sièges de clapets ; menues réparations et recharge en fluide frigorigène des pompes à chaleur.</p>';
        $h .= '<p><b>III. — Installations individuelles.</b> Chauffage et production d\'eau chaude, distribution d\'eau dans les parties privatives : 1. Dépenses d\'alimentation commune de combustible ; 2. Exploitation et entretien courant, menues réparations : a) réglage de débit et température de l\'ECS ; vérification et réglage des appareils de commande, d\'asservissement et de sécurité d\'aquastat et de pompe ; dépannage ; contrôle des raccordements et de l\'alimentation des chauffe-eau électriques ; vérification de l\'état des résistances et thermostats, nettoyage ; réglage des thermostats et contrôle de la température d\'eau ; contrôle et réfection d\'étanchéité des raccordements eau froide - eau chaude ; contrôle des groupes de sécurité ; rodage des sièges de clapets des robinets ; réglage des mécanismes de chasses d\'eau. b) Menues réparations : remplacement des bilames, pistons, membranes, boîtes à eau, allumage piézo-électrique, clapets et joints des appareils à gaz ; rinçage et nettoyage des corps de chauffe et tuyauteries ; remplacement des joints, clapets et presse-étoupes des robinets ; remplacement des joints, flotteurs et joints cloches des chasses d\'eau.</p>';
        $h .= '<p><b>IV. — Parties communes intérieures.</b> 1. Dépenses d\'électricité ; fournitures consommables (produits d\'entretien, balais et petit matériel, sel). 2. Exploitation et entretien courant, menues réparations : entretien de la minuterie, pose, dépose et entretien des tapis ; menues réparations des appareils d\'entretien de propreté (aspirateur). 3. Entretien de propreté (frais de personnel).</p>';
        $h .= '<p><b>V. — Espaces extérieurs.</b> 1. Dépenses d\'électricité ; essence et huile ; fournitures consommables (ampoules ou tubes d\'éclairage, engrais, produits bactéricides et insecticides, graines, fleurs, plants et plantes de remplacement, hors réfection de massifs, plates-bandes ou haies). 2. a) Exploitation et entretien courant : opérations de coupe, désherbage, sarclage, ratissage, nettoyage et arrosage des allées, aires de stationnement, abords, espaces verts, aires de jeux, bassins, fontaines, caniveaux et canalisations d\'évacuation des eaux pluviales ; entretien du matériel horticole ; remplacement du sable des bacs et du petit matériel de jeux. b) Peinture et menues réparations des bancs de jardins, des équipements de jeux et grillages.</p>';
        $h .= '<p><b>VI. — Hygiène.</b> 1. Dépenses de fournitures consommables : sacs en plastique et papier d\'élimination des rejets ; produits de désinsectisation et de désinfection, y compris des colonnes sèches de vide-ordures. 2. Exploitation et entretien courant : entretien et vidange des fosses d\'aisances ; entretien des appareils de conditionnement des ordures. 3. Élimination des rejets (frais de personnel).</p>';
        $h .= '<p><b>VII. — Équipements divers du bâtiment.</b> 1. La fourniture d\'énergie nécessaire à la ventilation mécanique. 2. Exploitation et entretien courant : ramonage des conduits de ventilation ; entretien de la ventilation mécanique ; entretien des dispositifs d\'ouverture automatique ou codée et des interphones ; visites périodiques (hors contrôles réglementaires de sécurité), nettoyage et graissage de l\'appareillage fixe de manutention des nacelles de nettoyage des façades vitrées. 3. Divers : abonnement des postes de téléphone à la disposition des locataires.</p>';
        $h .= '<p><b>VIII. — Impositions et redevances.</b> Droit de bail. Taxe ou redevance d\'enlèvement des ordures ménagères. Taxe de balayage.</p>';

        /* ═══════════════ 2) DÉCRET 87-712 — RÉPARATIONS LOCATIVES ═══════════════ */
        $h .= '<h2>Décret n° 87-712 du 26 août 1987 fixant la liste des réparations locatives</h2>';
        $h .= '<p><b>Article 1.</b> Sont des réparations locatives les travaux d\'entretien courant et de menues réparations, y compris les remplacements d\'éléments assimilables auxdites réparations, consécutifs à l\'usage normal des locaux et équipements à usage privatif. Ont notamment le caractère de réparations locatives les réparations énumérées en annexe au présent décret.</p>';
        $h .= '<p class="clabel">Annexe : Liste de réparations ayant le caractère de réparations locatives</p>';
        $h .= '<p><b>I. — Parties extérieures dont le locataire a l\'usage exclusif.</b> a) Jardins privatifs : entretien courant, notamment des allées, pelouses, massifs, bassins et piscines ; taille, élagage, échenillage des arbres et arbustes ; remplacement des arbustes ; réparation et remplacement des installations mobiles d\'arrosage. b) Auvents, terrasses et marquises : enlèvement de la mousse et des autres végétaux. c) Descentes d\'eaux pluviales, chéneaux et gouttières : dégorgement des conduits.</p>';
        $h .= '<p><b>II. — Ouvertures intérieures et extérieures.</b> a) Sections ouvrantes telles que portes et fenêtres : graissage des gonds, paumelles et charnières ; menues réparations des boutons et poignées de portes, des gonds, crémones et espagnolettes ; remplacement notamment de boulons, clavettes et targettes. b) Vitrages : réfection des mastics ; remplacement des vitres détériorées. c) Dispositifs d\'occultation de la lumière tels que stores et jalousies : graissage ; remplacement notamment de cordes, poulies ou de quelques lames. d) Serrures et verrous de sécurité : graissage ; remplacement de petites pièces ainsi que des clés égarées ou détériorées. e) Grilles : nettoyage et graissage ; remplacement notamment de boulons, clavettes, targettes.</p>';
        $h .= '<p><b>III. — Parties intérieures.</b> a) Plafonds, murs intérieurs et cloisons : maintien en état de propreté ; menus raccords de peintures et tapisseries ; remise en place ou remplacement de quelques éléments de revêtement (faïence, mosaïque, matière plastique) ; rebouchage des trous rendu assimilable à une réparation par le nombre, la dimension et l\'emplacement de ceux-ci. b) Parquets, moquettes et autres revêtements de sol : encaustiquage et entretien courant de la vitrification ; remplacement de quelques lames de parquets et remise en état, pose de raccords de moquettes et autres revêtements, notamment en cas de taches et de trous. c) Placards et menuiseries telles que plinthes, baguettes et moulures : remplacement des tablettes et tasseaux de placard et réparation de leur dispositif de fermeture ; fixation de raccords et remplacement de pointes de menuiseries.</p>';
        $h .= '<p><b>IV. — Installations de plomberie.</b> a) Canalisations d\'eau : dégorgement ; remplacement notamment de joints et de colliers. b) Canalisations de gaz : entretien courant des robinets, siphons et ouvertures d\'aération ; remplacement périodique des tuyaux souples de raccordement. c) Fosses septiques, puisards et fosses d\'aisance : vidange. d) Chauffage, production d\'eau chaude et robinetterie : remplacement des bilames, pistons, membranes, boîtes à eau, allumage piézo-électrique, clapets et joints des appareils à gaz ; rinçage et nettoyage des corps de chauffe et tuyauteries ; remplacement des joints, clapets et presse-étoupes des robinets ; remplacement des joints, flotteurs et joints cloches des chasses d\'eau. e) Éviers et appareils sanitaires : nettoyage des dépôts de calcaire, remplacement des tuyaux flexibles de douches.</p>';
        $h .= '<p><b>V. — Équipements d\'installations d\'électricité.</b> Remplacement des interrupteurs, prises de courant, coupe-circuits et fusibles, des ampoules, tubes lumineux ; réparation ou remplacement des baguettes ou gaines de protection.</p>';
        $h .= '<p><b>VI. — Autres équipements mentionnés au contrat de location.</b> a) Entretien courant et menues réparations des appareils tels que réfrigérateurs, machines à laver le linge et la vaisselle, sèche-linge, hottes aspirantes, adoucisseurs, capteurs solaires, pompes à chaleur, appareils de conditionnement d\'air, antennes individuelles de radiodiffusion et de télévision, meubles scellés, cheminées, glaces et miroirs ; b) Menues réparations nécessitées par la dépose des bourrelets ; c) Graissage et remplacement des joints des vidoirs ; d) Ramonage des conduits d\'évacuation des fumées et des gaz et conduits de ventilation.</p>';

        /* ═══════════════ 3) NOTICE LÉGALE D'INFORMATION (verbatim intégral) ═══════════════ */
        $h .= '<h2>Notice légale d\'information</h2>';
        $h .= '<p class="clabel">Préambule</p>';
        $h .= '<p>Le régime de droit commun des baux d\'habitation, applicable aux locations de logements constituant la résidence principale des locataires, est défini principalement par la loi n° 89-462 du 6 juillet 1989 tendant à améliorer les rapports locatifs. La présente notice d\'information rappelle les principaux droits et obligations des parties ainsi que certaines des voies de conciliation et de recours possibles pour régler leurs litiges. Si la plupart des règles s\'appliquent indifféremment à l\'ensemble des locations, la loi prévoit certains aménagements pour les locations meublées ou les colocations afin de prendre en compte les spécificités attachées à ces catégories de location. Pour prétendre à la qualification de meublé, un logement doit être équipé d\'un mobilier en nombre et en qualité suffisants pour permettre au locataire d\'y dormir, manger et vivre convenablement au regard des exigences de la vie courante (titre I<sup>er</sup> bis de la loi du 6 juillet 1989). La liste de ce mobilier est fixée par décret. Les colocations, définies comme la location d\'un même logement par plusieurs locataires, sont soumises au régime applicable le cas échéant aux locations nues ou meublées et aux règles spécifiques prévues par la loi en matière de colocation (art. 8-1).</p>';

        $h .= '<p class="clabel">1. Établissement du bail</p>';
        $h .= '<p><b>1.1. Forme et contenu du contrat.</b> Le contrat de location est établi par écrit et respecte un bail type défini par décret. Il peut être établi directement entre le bailleur et le locataire, éventuellement avec l\'aide d\'un intermédiaire (agent immobilier, administrateur de biens, commissaire de justice, notaire…). Il doit être fait en autant d\'originaux que de parties et remis à chacune d\'elles. Le contrat doit comporter certaines mentions, notamment l\'identité des parties, la description du logement, sa surface habitable et les conditions financières. En cas d\'inexactitude supérieure à 5 % de la surface habitable mentionnée au bail d\'une location nue, le locataire peut demander une diminution de loyer proportionnelle à l\'écart constaté (art. 3 et 3-1). Certaines clauses sont interdites et réputées non écrites : celles imposant le prélèvement automatique comme mode de paiement, prévoyant des pénalités en cas de retard, interdisant au locataire d\'héberger des personnes ne vivant pas habituellement avec lui, prévoyant des frais de délivrance ou d\'envoi de quittance, etc. (art. 4). Le bailleur est tenu de remettre au locataire un certain nombre de documents lors de la signature du contrat, notamment un dossier de diagnostic technique incluant le DPE (art. 3-3).</p>';
        $h .= '<p><b>1.2. Durée du contrat.</b> Location d\'un logement nu : le bail est conclu pour une durée minimum de trois ans lorsque le bailleur est une personne physique ou une société civile immobilière familiale, et de six ans lorsqu\'il est une personne morale. À défaut de congé, le bail est renouvelé ou reconduit automatiquement dans les mêmes conditions pour trois ou six ans selon le cas (art. 10). Par exception, la durée peut être inférieure à trois ans, mais d\'au minimum un an, si le bailleur personne physique (ou membre d\'une SCI familiale ou d\'une indivision) prévoit de reprendre son logement pour des raisons familiales ou professionnelles, mentionnées au bail. Le bailleur confirme la reprise par lettre recommandée avec avis de réception au minimum deux mois avant la fin du bail (art. 11). Location d\'un logement meublé : le contrat est conclu pour une durée d\'au moins un an, reconduite automatiquement à défaut de congé ; pour un étudiant, une durée de neuf mois non reconductible tacitement est possible (art. 25-7).</p>';
        $h .= '<p><b>1.3. Conditions financières.</b> <b>1.3.1. Loyer.</b> Le loyer initial est en principe fixé librement entre les parties. Toutefois, depuis le 24 août 2022, lorsqu\'un logement est classé F ou G par le DPE (passoires thermiques), aucune augmentation de loyer ne peut être effectuée à la nouvelle location. Dans les zones tendues, les loyers peuvent être encadrés : au moment de la relocation, le loyer ne peut excéder le dernier loyer appliqué revalorisé de l\'IRL (sauf travaux d\'amélioration ou loyer manifestement sous-évalué) ; et là où un arrêté préfectoral fixe des références de loyers, le loyer au m² ne peut excéder le loyer de référence majoré, sauf complément de loyer justifié par des caractéristiques de localisation ou de confort et mentionné au contrat. La révision annuelle du loyer (art. 17-1) n\'est possible que si une clause le prévoit, dans la limite de la variation de l\'IRL publié par l\'INSEE, et est impossible pour les logements F ou G ; le bailleur dispose d\'un an à compter de la date de révision pour la demander, sans effet rétroactif. Au renouvellement (art. 17-2 et 25-9), le loyer n\'est réévalué que s\'il est manifestement sous-évalué (hors F/G), selon la procédure de proposition, de saisine de la commission départementale de conciliation et, à défaut d\'accord, du juge, avec étalement de la hausse.</p>';
        $h .= '<p><b>1.3.2. Charges locatives (art. 23).</b> Les charges récupérables, limitativement énumérées par décret (huit postes), sont récupérées de manière ponctuelle sur justificatifs ou par provisions périodiques avec régularisation annuelle comparant les provisions versées aux dépenses effectives. Le bailleur communique le décompte par nature de charges, le mode de répartition en immeuble collectif et une note d\'information sur le calcul des charges de chauffage et d\'ECS collectives, et tient les pièces justificatives à disposition pendant six mois. Pour un logement meublé ou une colocation, les charges peuvent être récupérées au forfait, fixé à la conclusion du contrat et non régularisable, non manifestement disproportionné (art. 8-1 et 25-10).</p>';
        $h .= '<p><b>1.3.3. Contribution au partage des économies de charges (art. 23-1).</b> Une contribution peut être demandée au locataire après des travaux d\'économie d\'énergie réalisés par le bailleur, limitée à quinze ans, d\'un montant fixe et non révisable ne pouvant excéder la moitié de l\'économie d\'énergie estimée, sous conditions.</p>';
        $h .= '<p><b>1.3.4. Modalités de paiement.</b> Le loyer et les charges sont payés à la date prévue au contrat. Le bailleur transmet gratuitement une quittance sur demande, distinguant loyer et charges ; aucun frais de gestion d\'avis d\'échéance ou de quittance ne peut être facturé (art. 21).</p>';
        $h .= '<p><b>1.4. Garanties.</b> <b>1.4.1. Dépôt de garantie (art. 22).</b> Son montant figure au bail ; il ne peut excéder un mois de loyer hors charges (location nue), deux mois (meublé), et n\'est pas révisable. <b>1.4.2. Garantie autonome (art. 22-1-1)</b> : engagement du garant de verser une somme en cas de défaillance, dans la limite du dépôt de garantie. <b>1.4.3. Cautionnement (art. 22-1)</b> : acte écrit signé par la caution comportant les mentions obligatoires (montant du loyer, conditions de révision, faculté de résiliation, mention de l\'article 2297 du code civil) ; le bailleur ne peut cumuler cautionnement et assurance des risques locatifs (sauf étudiant/apprenti).</p>';
        $h .= '<p><b>1.5. État des lieux (art. 3-2).</b> Établi contradictoirement à l\'entrée et à la sortie, il décrit l\'état du logement et ses équipements. À défaut d\'état des lieux d\'entrée, le logement est présumé délivré en bon état. Le locataire peut demander à le compléter dans les dix jours (ou durant le premier mois de la période de chauffe). En cas de désaccord, recours à un commissaire de justice, frais partagés par moitié. En meublé, un inventaire et un état détaillé du mobilier sont établis sans surcoût (art. 25-5).</p>';

        $h .= '<p class="clabel">2. Droits et obligations des parties</p>';
        $h .= '<p><b>2.1. Obligations générales du bailleur (art. 6).</b> Délivrer un logement décent, ne laissant pas apparaître de risques manifestes pour la sécurité ou la santé, exempt d\'infestation d\'espèces nuisibles et parasites, répondant à un critère de performance énergétique minimale et doté des éléments de confort. À compter du 1<sup>er</sup> janvier 2025, le logement décent doit être compris entre la classe A et F du DPE ; entre A et E à compter du 1<sup>er</sup> janvier 2028 ; entre A et D à compter du 1<sup>er</sup> janvier 2034. Le bailleur doit délivrer un logement en bon état d\'usage et de réparations, l\'entretenir, effectuer les réparations autres que locatives, assurer une jouissance paisible, ne pas s\'opposer aux simples aménagements du locataire, et transmettre les informations relatives à la consommation de chaleur, de froid et d\'eau chaude sanitaire (art. 6-2) et à la qualité de l\'eau (art. 6-3).</p>';
        $h .= '<p><b>2.2. Obligations générales du locataire (art. 7).</b> Payer le loyer et les charges aux dates convenues ; user paisiblement du logement conformément à sa destination et au règlement de copropriété ; ne pas sous-louer sans accord écrit du bailleur (loyer au m² du sous-locataire n\'excédant pas celui du locataire principal) ; ne pas réaliser de travaux de transformation sans accord écrit (le locataire peut toutefois réaliser des travaux d\'adaptation au handicap/perte d\'autonomie ou de rénovation énergétique, accord tacite du bailleur après deux mois de silence) ; laisser exécuter certains travaux décidés par le bailleur (réparations urgentes, amélioration, performance énergétique, mise aux normes de décence) ; prendre en charge l\'entretien courant, les menues réparations et les réparations locatives (sauf vétusté, malfaçon, vice de construction, cas fortuit ou force majeure) ; répondre des dégradations sauf preuve contraire ; s\'assurer contre les risques locatifs et le justifier chaque année.</p>';
        $h .= '<p><b>2.3. Lutte contre les nuisibles.</b> Le bailleur délivre et maintient un logement exempt d\'infestation ; le locataire suit les recommandations (stop-punaises.gouv.fr), informe le bailleur en cas d\'infestation et permet l\'accès pour les traitements. En cas de désaccord, saisine de la commission départementale de conciliation (art. 20-1). Information juridique : 0806 706 806 (ADIL).</p>';

        $h .= '<p class="clabel">3. Fin de contrat et sortie du logement</p>';
        $h .= '<p><b>3.1. Congés (art. 15 et 25-8).</b> <b>Congé du locataire</b> : à tout moment, par LRAR, acte de commissaire de justice ou remise en main propre contre récépissé. Préavis de trois mois en location nue, réduit à un mois en zone tendue ou en cas de motif prévu (premier emploi, mutation, perte ou nouvel emploi, état de santé, RSA/AAH, attribution d\'un logement social, violences familiales) ; un mois en meublé. <b>Congé du bailleur</b> : à l\'échéance du bail, pour reprise (occupation par lui-même ou un proche, justifiée), pour vente (le locataire est prioritaire, le congé valant offre de vente en location nue), ou pour motif légitime et sérieux. Préavis de six mois en location nue (avec notice d\'information), trois mois en meublé. Le congé frauduleux est sanctionné (amende jusqu\'à 6 000 € ou 30 000 € pour une personne morale).</p>';
        $h .= '<p><b>3.2. Sortie du logement.</b> <b>3.2.1. État des lieux de sortie</b> : établi entre les parties selon les mêmes modalités qu\'à l\'entrée ; en cas de mandat d\'un tiers par le bailleur, aucun frais ne peut être facturé au locataire. <b>3.2.2. Restitution du dépôt de garantie (art. 22)</b> : dans un délai maximal de deux mois à compter de la remise des clés (réduit à un mois si l\'état des lieux de sortie est conforme à celui d\'entrée), déduction faite des sommes justifiées dues. À défaut de restitution dans les délais, le montant dû est majoré de 10 % du loyer mensuel par mois de retard commencé.</p>';

        $h .= '<p class="clabel">4. Départ du conjoint victime de violences (art. 8-2)</p>';
        $h .= '<p>Lorsque le conjoint, partenaire de PACS ou concubin notoire quitte le logement en raison de violences exercées au sein du couple ou sur un enfant, il en informe le bailleur par LRAR accompagnée de la copie de l\'ordonnance de protection ou d\'une condamnation pénale de moins de six mois. La solidarité du locataire victime et de sa caution prend fin le lendemain de la première présentation du courrier au bailleur, pour les dettes nées à compter de cette date. Le non-paiement du loyer par l\'auteur des violences constitue un motif légitime et sérieux.</p>';

        $h .= '<p class="clabel">5. Règlement des litiges locatifs</p>';
        $h .= '<p><b>5.1. Prescription (art. 7-1).</b> En matière locative, l\'action se prescrit en principe par trois ans (un an pour l\'action en révision de loyer).</p>';
        $h .= '<p><b>5.2. Règlement amiable et conciliation.</b> Il est conseillé d\'adresser une LRAR à l\'autre partie exposant précisément les faits, avec arguments et preuves, avant tout recours. La <b>commission départementale de conciliation</b> (CDC), gratuite, composée à parts égales de représentants des bailleurs et des locataires, s\'efforce de concilier les parties dans un délai de deux mois. Sa saisine est un préalable obligatoire pour certains litiges (ajustement de loyer au renouvellement, encadrement des loyers, zones tendues) et facultatif pour d\'autres (dépôt de garantie, état des lieux, charges, réparations, décence, congés).</p>';
        $h .= '<p><b>5.3. Action en justice.</b> Tout litige relatif à un bail d\'habitation relève du tribunal judiciaire du lieu du logement. <b>5.3.2. Résiliation (art. 24).</b> Mise en œuvre de la clause résolutoire de plein droit dans quatre cas : défaut de paiement du loyer et des charges, non-versement du dépôt de garantie, défaut d\'assurance, troubles de voisinage constatés par décision de justice. Le bailleur fait signifier un commandement de payer (délai de deux mois ; un mois pour défaut d\'assurance) mentionnant la faculté de saisir le FSL ; à défaut de régularisation, il assigne le locataire pour faire constater la résiliation. À défaut de clause résolutoire, le bailleur peut demander la résiliation judiciaire, le juge appréciant la gravité de la faute. L\'assignation aux fins d\'expulsion est notifiée au préfet deux mois avant l\'audience, permettant la réalisation d\'un diagnostic social et financier ; le juge peut accorder des délais de paiement (jusqu\'à trois ans) ou ordonner l\'expulsion assortie d\'un délai de grâce.</p>';
        $h .= '<p><b>5.4. Prévention des expulsions.</b> Fonds de solidarité pour le logement (FSL), commission de surendettement, commission de coordination des actions de prévention des expulsions locatives (CCAPEX). <b>5.5.</b> Recherche d\'un logement adapté et droit au logement opposable (DALO). <b>5.6. Procédure d\'expulsion.</b> Le locataire ne peut être expulsé que sur décision de justice (l\'expulsion par le bailleur lui-même est passible de trois ans de prison et 30 000 € d\'amende) ; commandement de quitter les lieux, délai de deux mois, concours de la force publique par le préfet. <b>Trêve hivernale</b> du 1<sup>er</sup> novembre au 31 mars, suspendant l\'exécution forcée des expulsions (sauf exceptions).</p>';

        $h .= '<p class="clabel">6. Contacts utiles</p>';
        $h .= '<p>Les ADIL (agences départementales d\'information sur le logement) apportent un conseil gratuit, neutre et personnalisé (www.anil.org). Organismes payeurs des aides au logement : CAF, MSA. Associations représentatives nationales des bailleurs (UDLI, FEI, UNPI) et des locataires (CNL, CGL, CSF, CLCV, AFOC). Maisons de justice et du droit et points d\'accès au droit (www.annuaires.justice.gouv.fr). Ministère de la transition écologique (www.ecologie.gouv.fr). DossierFacile, le dossier de location numérique de l\'État (www.dossierfacile.fr). Site officiel www.service-public.fr ; Allo Service Public 3939.</p>';

        $h .= '</div>';
        return $h;
    }
}
